name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version
          cache: npm

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: node-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}

      - run: corepack enable

      - name: npm install
        run: |
          npm ci

      - name: Run test
        run: |
          npm run test
